### ISSUE TITLE
Etherscan reports AZP as an ERC-20, not an ERC-721, token.

### ISSUE THREAD

**Issue by sivner-figbus** [urbit/azimuth#29] opened 2020-07-09 09:52 UTC
Etherscan reports azimuth points as ERC-20 tokens.

This might relate to #8 .

Here, for instance, is the address which owns ~zod:

https://etherscan.io/address/0x3B17d097D9dd711e4Ef8517AbBF18B2Ba64381fe#tokentxns

![image](https://user-images.githubusercontent.com/67953485/87023790-29640300-c1d0-11ea-99a9-9ba880701528.png)

**Comment by Fang-** [comment] 2020-07-09 16:25
> This might relate to #8 .

I'm pretty sure that's the root cause of this, yes. As such, closing this as a duplicate of that, but thanks for filing regardless!

**Comment by jtobin** [comment] 2020-07-21 11:07
Closing per above comment.

**Closed by jtobin** 2020-07-21 11:07 UTC
